/*
 * @Description: 
 * @Author: Tong Chen
 * @Date: 2022-08-21 22:31:03
 * @LastEditTime: 2022-08-25 22:20:52
 * @LastEditors:  
 */

const centresName = [ // 34
  "Welfare Pharmacy",
  "Stubley Medical Centre",
  "Page Hall Pharmacy",
  "NHS Vaccination Centre",
  "Seven Hills Pharmacy",
  "Archway Pharmacy",
  "Seven Hills Pharmacy",
  "St. Oswald's Church",
  "Vantage Pharmacy",
  "Brookside Pharmacy",
  "Good Measure Pharmacy",
  "Westfield Com. Centre",
  "Mansfield Vaccine Centre",
  "Rosemary Street Pharmacy",
  "Swift Pharmacy Burngreave",
  "UK Pharmacy LTD",
  "Wise Methodist Church",
  "HEALTH CARE LTD",
  "Meadowgreen Centre",
  "W & Co. Centre",
  "Morrisons Pharmacy",
  "Swift Pharmacy Burngreave",
  "Hathersage Pharmacy",
  "Brimington Pharmacy",
  "Cohens Chemist",
  "Whalley Range Tennis and Cricket Club",
  "Forum Vaccination Hub",
  "One Stockport Hub",
  "Boots Stockport Vaccination Centre",
  "Larkhill Centre Timperley",
  "MFT ORC Vaccine Clinic",
  "Limelight Pharmacy",
  "Trinity Methodist Church",
  "Elliotts Pharmacy"
]

const manufacturerName = [ // 69
  "NISSIN Easson Factory",
  "TOYO Enterprise",
  "CNC-Takag Formi",
  "Awea Matech",
  "Cinnamon Manufacturing",
  "Barket Knitwear Manufacturing",
  "F. & B. Hosiery Manufacturing",
  "Sogotec UVA",
  "Leadwell Laser",
  "Palmary Virker",
  "Little Giant",
  "R-Tek Manufacturing Ltd",
  "kTech Silnas Manufacturing",
  "Spring Factory",
  "Hendersons Relish",
  "Menzi Factory",
  "M & D Matals Manufacturing",
  "Multi-Blend Chemicals Ltd",
  "Xpose Limited Manufacturing",
  "Donpui New Factory",
  "Catalent Manufacturing",
  "Glaxo Smith Kline",
  "Chatham House",
  "BioPharma Factory",
  "Watson-Marlow",
  "Harwell Factory",
  "Bolton Engineering & Manufacturing Co",
  "MPGL Ltd",
  "Aleppo Premium Ltd",
  "Glendale MPM Ltd",
  "Ancoats Factory",
  "AM Wonky Factory",
  "Padis Manufacturing",
  "Melt Puzl Manufacturing",
  "Power AIRSNAX Ltd",
  "Accraply Europe Manufacturing",
  "Medi Contract Manufacturer",
  "Cascade UK Ltd",
  "John Hogg Tech Manufacturing",
  "Cargill Plc",
  "Robant Manufacturer",
  "WestMill Ltd",
  "Cedyr Lab Factory",
  "Knitland Ltd",
  "Riley Ltd",
  "Flava Manufacturing",
  "Carlick Cont Ltd",
  "J & Z Sysmrt Ltd",
  "Catering Medical Manufacturing LTD",
  "Unilever POP Manufacturing",
  "Himalayan Manufacturer",
  "H & J Factory",
  "Auod Commer Ltd",
  "Welsolt Ltd",
  "Chadwick Texlis Ltd",
  "Fani Hillclare Manufacturing",
  "Afix Mozzarella Factory",
  "Jams Galt & Co. Ltd",
  "Ricoman Liggt Manufacturing",
  "Upholstery Ltd",
  "De Lacy Ltd",
  "PZ Cussons Manufacturing",
  "Surgitrac Instr Manufacturing",
  "Encore Pik Ltd",
  "Extons Manufacturing",
  "Brintannic Factory",
  "Noble Cafu Manufacturing",
  "Boxer Manufacturing Ltd",
  "NorCabins Ltd"
]

module.exports = {
  centresName,
  manufacturerName
}